PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS chaupai_verses;
CREATE TABLE chaupai_verses (
  id TEXT PRIMARY KEY,
  source_type TEXT NOT NULL,
  title TEXT NOT NULL,
  day_index INTEGER,
  date TEXT,
  gurmukhi_text TEXT NOT NULL,
  english_meaning TEXT NOT NULL,
  simple_explanation TEXT NOT NULL,
  life_reflection TEXT NOT NULL,
  is_featured INTEGER NOT NULL DEFAULT 0,
  audio_file_name TEXT,
  tags_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_chaupai_day_index ON chaupai_verses(day_index);
CREATE INDEX idx_chaupai_title ON chaupai_verses(title);
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-001', 'chaupai_sahib', 'Protection in Remembrance', 3, NULL, 'ਹਮਰੀ ਕਰੋ ਹਾਥ ਦੈ ਰਛਾ ॥', 'Please protect me with Your own hand.', 'This is a prayer of surrender and courage, not fear.', 'Walk into one difficult conversation today with humility and inner steadiness.', 1, NULL, '["courage","prayer"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-002', 'chaupai_sahib', 'Kabi Bacha Benti Chaupai', 8, NULL, 'Kabi bacha benti chaupai', 'This is the beginning of the prayer (Chaupai) by Guru Gobind Singh Ji.', 'This prayer acts as a protective shield for all human beings and helps anyone suffering from fear or low self-confidence.', 'Approaching the Divine with a humble request creates mental armor against the anxieties of the world.', 0, NULL, '["protection","humility","confidence"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-003', 'chaupai_sahib', 'Hamri Karo Hath Dai Rachha', 9, NULL, 'Hamri karo hath dai rachha', 'Please provide protection with Your own hand.', 'The devotee asks the Almighty to personally intervene and extend a hand of protection.', 'True security is found when we surrender ego and ask for higher guidance and safety.', 0, NULL, '["protection","surrender"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-004', 'chaupai_sahib', 'Pooran Hoye Chit Ki Ichha', 10, NULL, 'Pooran hoye chit ki ichha', 'May all the desires of the heart be fulfilled.', 'This is a prayer that every righteous and sincere wish reaches completion through Divine grace.', 'When your intentions are pure, trust that the Universe supports their fulfillment.', 0, NULL, '["intention","grace"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-005', 'chaupai_sahib', 'Tav Charnan Man Rahe Hamara', 11, NULL, 'Tav charnan man rahe hamara', 'May my mind always remain at Your feet.', 'The goal is for consciousness to stay eternally attached to and focused on the presence of the Lord.', 'Spiritual stability comes from keeping your thoughts anchored in humility and devotion.', 0, NULL, '["devotion","focus"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-006', 'chaupai_sahib', 'Apna Jaan Karo Pritpala', 12, NULL, 'Apna jaan karo pritpala', 'Cherish and protect me as Your own.', 'The devotee asks the Lord to nourish and sustain them with love and care like a child.', 'Knowing you belong to the Divine brings a deep and steady peace.', 0, NULL, '["belonging","peace","care"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-007', 'chaupai_sahib', 'Hamre Dusht Sabai Tum Ghaihu', 13, NULL, 'Hamre dusht sabai tum ghaihu', 'May You destroy all my enemies.', 'In this context, enemies are internal vices such as lust, anger, greed, attachment, and ego.', 'Your greatest battles are internal; ask for help to overcome negative impulses.', 0, NULL, '["vices","discipline","inner-work"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-008', 'chaupai_sahib', 'Aapu Hath Dai Mohi Bachaihu', 14, NULL, 'Aapu hath dai mohi bachaihu', 'Save me with Your own hand.', 'This is a specific plea to be rescued from the five internal vices that can lead a person astray.', 'Deep-seated habits are hard to change alone; ask Divine strength to lift you from negative patterns.', 0, NULL, '["rescue","vices","support"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-009', 'chaupai_sahib', 'Sukhi Basai Moro Parivara', 15, NULL, 'Sukhi basai moro parivara', 'May my family live in happiness.', 'The prayer extends beyond the individual and asks for peace, harmony, and well-being for the entire household.', 'Personal spirituality is incomplete without wishing happiness and tranquility for those around you.', 0, NULL, '["family","harmony","wellbeing"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-010', 'chaupai_sahib', 'Sevak Sikh Sabai Kartara', 16, NULL, 'Sevak sikh sabai kartara', 'May all Your servants and disciples live in peace.', 'The devotee prays for the whole community of seekers and faithful followers of the Creator.', 'As faith grows, the heart naturally expands to seek welfare for all.', 0, NULL, '["community","sarbat-da-bhala","peace"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-011', 'chaupai_sahib', 'Mo Rachha Nij Kar Dai Kariyai', 17, NULL, 'Mo rachha nij kar dai kariyai', 'Personally protect me with Your own hand.', 'This final emphasis asks for personal protection against internal vices that disturb the mind.', 'Consistent prayer for protection strengthens the shield that keeps the mind clear and virtuous.', 0, NULL, '["protection","clarity","virtue"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-012', 'chaupai_sahib', 'Sabh Bairan Ko Aaj Sanghariye', 18, NULL, 'सभ बैरन को आज संघारिए (Sabh bairan ko aaj sanghariye)', 'The devotee prays for the destruction of all enemies today.', 'In this spiritual context, enemies refers to internal vices like lust, anger, greed, and ego.', 'True victory begins by asking for strength to conquer the negative impulses within yourself.', 0, NULL, '["vices","discipline","victory"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-013', 'chaupai_sahib', 'Pooran Hoye Hamari Aasa', 19, NULL, 'पूरन होय हमारी आसा (Pooran hoye hamari aasa)', 'May all my hopes and righteous desires be fulfilled by Your grace.', 'This is a plea that sincere and virtuous aspirations reach completion through Divine support.', 'When you align your desires with righteousness, trust in their eventual fulfillment.', 0, NULL, '["hope","grace","righteousness"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-014', 'chaupai_sahib', 'Tav Bhajan Ki Rahe Pyasa', 20, NULL, 'तव भजन की रहे प्यासा (Tav bhajan ki rahe pyasa)', 'May I always have a spiritual thirst and longing for Your meditation and praise.', 'The devotee asks to never lose the deep longing to remember and connect with the Almighty through prayer.', 'Keeping spiritual thirst alive helps you remain constantly connected to the Source of peace.', 0, NULL, '["longing","prayer","connection"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-015', 'chaupai_sahib', 'Tumhe Chhaad Koi Avar Na Dhyaoon', 21, NULL, 'तुम्हें छाड कोई अवर न ध्याऊं (Tumhe chhaad koi avar na dhyaoon)', 'I should never meditate on anyone else but You; I should only remember You day and night.', 'This verse emphasizes exclusive devotion, stating that the devotee will not look to any other power for support.', 'Unwavering focus on the One Divine leads to mental clarity and spiritual stability.', 0, NULL, '["devotion","focus","stability"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-016', 'chaupai_sahib', 'Jo Bar Chahoon Tum Te Paoon', 22, NULL, 'जो बर चाहूं तुम ते पाऊं (Jo bar chahoon tum te paoon)', 'Whatever blessings or boons I desire, I should receive them only from You.', 'This reinforces the idea that God is the sole Giver of all spiritual and worldly gifts.', 'Recognizing the ultimate Source of blessings helps you remain humble and grateful.', 0, NULL, '["blessings","humility","gratitude"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-017', 'chaupai_sahib', 'Sevak Sikh Hamare Tariye', 23, NULL, 'सेवक सिख हमारे तारिए (Sevak sikh hamare tariye)', 'O Guru, please ferry my disciples and servants across the difficult ocean of worldly existence.', 'A request for the Lord to guide and save all faithful seekers from suffering and cycles of the world.', 'True leadership includes praying for the liberation and well-being of the whole community.', 0, NULL, '["community","leadership","liberation"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-018', 'chaupai_sahib', 'Chun-Chun Shatru Hamare Mariye', 24, NULL, 'चुन चुन शत्रु हमारे मारिए (Chun-chun shatru hamare mariye)', 'Pick out and destroy my enemies, the negative internal impulses that plague me.', 'This is a call for the Lord to systematically eliminate specific internal vices that hinder spiritual growth.', 'Ask for Divine help to target and remove deeply rooted habits that hold you back.', 0, NULL, '["inner-work","vices","growth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-019', 'chaupai_sahib', 'Aap Hath Dai Mujhai Ubariye', 25, NULL, 'आप हाथ दै मुझै उबरिए (Aap hath dai mujhai ubariye)', 'Protect me with Your own hand and save me from this worldly ocean.', 'A direct plea for the Lord to personally reach out and rescue the devotee from worldly attachments and fears.', 'Acknowledging your need for Divine rescue is the first step toward receiving it.', 0, NULL, '["rescue","attachments","faith"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-020', 'chaupai_sahib', 'Maran Kaal Ka Traas Nivariye', 26, NULL, 'मरण काल का त्रास निवरिए (Maran kaal ka traas nivariye)', 'Remove the fear of death that constantly looms over me.', 'This prayer asks the Lord to take away anxiety and terror associated with the end of life.', 'Spiritual connection gives courage to face mortality with peace instead of fear.', 0, NULL, '["fear","mortality","courage"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-021', 'chaupai_sahib', 'Hoo Sada Hamare Pakhha', 27, NULL, 'हूसदा हमारे पक्खा (Hoo sada hamare pakhha)', 'O Waheguru, always remain on my side and continue to support me.', 'The devotee asks for the constant presence and backing of the Divine in every situation.', 'Knowing the Almighty is on your side gives confidence to face any challenge.', 0, NULL, '["support","presence","confidence"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-022', 'chaupai_sahib', 'Sri Asidhuj Joo Kariyahu Rakkha', 28, NULL, 'श्री असिधुज जू करियहु रक्खा (Sri asidhuj joo kariyahu rakkha)', 'O Bearer of the Sword of Justice, always provide me with Your protection.', 'The Lord is invoked as Asidhuj, one who carries the sword, to guard and shield the devotee from harm.', 'Divine protection is an active force that stands between you and negativity.', 0, NULL, '["justice","protection","strength"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-023', 'chaupai_sahib', 'Rakho Rakhanhare Mujhai', 29, NULL, 'राख लेहु मोहे राखनहारे (Rakho rakhanhare mujhai)', 'O Protector of the entire creation, please protect me as well.', 'The devotee recognizes God as the universal guardian and seeks a personal place under that protection.', 'The same power that sustains the universe can protect you personally too.', 0, NULL, '["guardian","trust","safety"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-024', 'chaupai_sahib', 'Saheb Sant Sahaaye Piyare', 30, NULL, 'साहिब संत सहाए पियारे (Saheb sant sahaaye piyare)', 'You are the beloved master and the support of all saintly beings.', 'God is described as friend and helper to those who walk the path of holiness and truth.', 'When you strive for virtue, you gain support from the ultimate Master.', 0, NULL, '["virtue","support","truth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-025', 'chaupai_sahib', 'Deen Bandhu Dushtan Ke Hanta', 31, NULL, 'दीन बंधु दुष्टन के हंता (Deen bandhu dushtan ke hanta)', 'You are the friend of the poor and the destroyer of the wicked.', 'This describes Divine compassion for the humble and firmness against evil.', 'Divinity uplifts the lowly and stands powerfully against injustice and vice.', 0, NULL, '["compassion","justice","humility"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-026', 'chaupai_sahib', 'Tumo Ho Puri Chatur Das Kanta', 32, NULL, 'तुम हो पुरी चतुर दस कंता (Tumo ho puri chatur das kanta)', 'You are the Master of all the fourteen worlds.', 'The verse acknowledges the absolute sovereignty of God over every realm and dimension.', 'Remembering Divine vastness helps place personal problems into perspective.', 0, NULL, '["sovereignty","perspective","awe"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-027', 'chaupai_sahib', 'Kaal Paye Brahma Bap Dhara', 33, NULL, 'काल पाए ब्रह्मा बप धरा (Kaal paye Brahma bap dhara)', 'By the Will of God and Time, Brahma took physical form.', 'Even Brahma manifested only by command and timing of the Supreme Power.', 'Everything in existence, no matter how powerful, remains subject to Eternal Will.', 0, NULL, '["eternal-will","timing","humility"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-028', 'chaupai_sahib', 'Kaal Paye Shivju Avtara', 34, NULL, 'काल पाए शिवजू अवतारा (Kaal paye Shivju avtara)', 'By the Will of God, Shiva was born and manifested.', 'Shiva''s manifestation was determined by the Infinite Power.', 'All manifestations of spiritual power arise from the same One Source.', 0, NULL, '["one-source","manifestation","divine-will"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-029', 'chaupai_sahib', 'Kaal Paye Vishnu Prakash Bhaya', 35, NULL, 'काल पाए विष्णू प्रकाश भया (Kaal paye Vishnu prakash bhaya)', 'By the Will and Time of God, Vishnu was revealed.', 'Vishnu appeared only through Divine command at the appointed time.', 'Divine timing governs major shifts and revelations in life.', 0, NULL, '["timing","revelation","trust"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-030', 'chaupai_sahib', 'Sakal Kaal Ka Kiya Tamasha', 36, NULL, 'सकल काल का किया तमाशा (Sakal kaal ka kiya tamasha)', 'This entire world is a spectacle created by the Almighty Power.', 'The world is seen as a grand play orchestrated by the Lord of Time.', 'Seeing life as Divine play can help you hold worldly stress with more detachment.', 0, NULL, '["detachment","worldview","peace"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-031', 'chaupai_sahib', 'Javan Kaal Jogi Shiv Kiyo', 37, NULL, 'जवन काल जोगी शिव कियो (Javan kaal jogi Shiv kiyo)', 'The Power that created Shiva as a Yogi.', 'The Supreme Power shaped and inspired Shiva to become a master of meditation.', 'All spiritual achievements and roles are gifts from the ultimate Creator.', 0, NULL, '["meditation","creator","spiritual-growth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-032', 'chaupai_sahib', 'Ved Raaj Brahma Joo Thiyo', 38, NULL, 'वेद राज ब्रह्मा जू थियो (Ved raaj Brahma joo thiyo)', 'The same Power that created Brahma, the king of the Vedas.', 'The Supreme Power (Akaal) brought forth Brahma, the deity associated with creation of the Vedas.', 'Every source of knowledge and creation has its origin in the one Divine Power.', 0, NULL, '["knowledge","origin","divine-power"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-033', 'chaupai_sahib', 'Sakal Kaal Ko Kiya Pranam', 39, NULL, 'सकल काल को किया प्रणाम (Sakal kaal ko kiya pranam)', 'I salute that Supreme Power who created the whole universe.', 'The devotee offers deep salutations to the Almighty, Master of Time and Architect of the cosmos.', 'Recognizing the Creator''s vastness helps cultivate awe and humble surrender.', 0, NULL, '["salutation","awe","surrender"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-034', 'chaupai_sahib', 'Javan Jagat Sabh Kiyo Sawari', 40, NULL, 'जवन जगत सभ कियो सवारी (Javan jagat sabh kiyo sawari)', 'The One who created and organized the entire world and its beings.', 'The Lord created the world and also organized and adorned it with all living creatures.', 'There is Divine order and purpose behind the structure of the world and our place in it.', 0, NULL, '["order","creation","purpose"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-035', 'chaupai_sahib', 'Dev Dait Yakhhan Upajai', 41, NULL, 'देव दैत यच्छन उपजाई (Dev dait yakhhan upajai)', 'The Lord who created gods, demons, and powerful spirits.', 'The Almighty is the source of all beings, from the divine and powerful to the demonic.', 'All forces in the universe, whether positive or negative, originate from one Source.', 0, NULL, '["one-source","beings","cosmos"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-036', 'chaupai_sahib', 'Aadi Ant Ekae Avtara', 42, NULL, 'आदि अंत एकै अवतारा (Aadi ant ekae avtara)', 'He is the same unique manifestation from the beginning to the end.', 'God remains constant and unchanging from the start of creation to its conclusion.', 'In a changing world, the Divine is the most reliable anchor.', 0, NULL, '["constant","anchor","eternal"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-037', 'chaupai_sahib', 'Soee Guru Samjhiyahu Hamara', 43, NULL, 'सोई गुरु समझियहु हमारा (Soee Guru samjhiyahu hamara)', 'Understand that He alone is our true Guru.', 'We should recognize the Almighty as the ultimate and only true Teacher.', 'Seeking guidance from the Divine Source helps keep us on the path of truth.', 0, NULL, '["guru","guidance","truth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-038', 'chaupai_sahib', 'Namaskar Tis Hi Ko Hamari', 44, NULL, 'नमस्कार तिस ही को हमारी (Namaskar tis hi ko hamari)', 'My humble salutations are to Him alone.', 'The devotee bows in complete reverence to the unique and Supreme Lord.', 'Direct devotion to the One Source keeps worship focused and steady.', 0, NULL, '["reverence","one-source","devotion"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-039', 'chaupai_sahib', 'Sakal Praja Jin Aap Sawari', 45, NULL, 'सकल प्रजा जिन आप सवारी (Sakal praja jin aap sawari)', 'He who Himself takes care of and sustains all His subjects.', 'The Lord personally nurtures and protects every living being He has created.', 'You are not alone; the Creator is personally involved in your well-being.', 0, NULL, '["care","sustenance","wellbeing"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-040', 'chaupai_sahib', 'Sivakan Ko Sivagan Sukh Diyo', 46, NULL, 'शिवकंद को शिवगण सुख दियो (Sivakan ko sivagan sukh diyo)', 'The Lord who has given welfare and happiness to His servants.', 'The Almighty grants true peace, welfare, and joy to those who serve with devotion.', 'Service to the Divine brings fulfillment the world cannot provide.', 0, NULL, '["service","joy","welfare"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-041', 'chaupai_sahib', 'Shatruan Ko Pal Mo Badh Kiyo', 47, NULL, 'शत्रुअन को पल मो बध कीयो (Shatruan ko pal mo badh kiyo)', 'Who destroyed the enemies (vices) in a single moment.', 'The Lord has power to instantly eliminate internal enemies of the mind.', 'No matter how strong negative habits feel, Divine grace can clear them swiftly.', 0, NULL, '["vices","grace","transformation"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-042', 'chaupai_sahib', 'Ghat Ghat Ke Antar Ki Janat', 48, NULL, 'घट घट के अंतर की जानत (Ghat ghat ke antar ki janat)', 'The Lord who knows what is inside every heart.', 'God is the All-Knower who understands the most private thoughts and feelings of all.', 'Since God knows true intentions, prioritize inner honesty over outward show.', 0, NULL, '["all-knowing","honesty","heart"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-043', 'chaupai_sahib', 'Bhale Bure Ki Peer Pachhanat', 49, NULL, 'भले बुरे की पीर पछानत (Bhale bure ki peer pachhanat)', 'He recognizes and understands the pain of both good and bad people.', 'The Lord''s empathy is universal and recognizes the suffering of everyone.', 'Divine compassion is not limited; every soul in pain is heard.', 0, NULL, '["compassion","empathy","mercy"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-044', 'chaupai_sahib', 'Cheeti Te Kunchar Asthoola', 50, NULL, 'चींटी ते कुंचर अस्थाूला (Cheeti te kunchar asthoola)', 'From the tiny ant to the large elephant.', 'The Lord''s attention spans all life, from the smallest insect to the largest animal.', 'No being is too small or insignificant to be noticed by the Divine.', 0, NULL, '["creation","care","inclusion"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-045', 'chaupai_sahib', 'Sabh Par Kripa Dristi Kar Phoola', 51, NULL, 'सभ पर कृपा दृष्टि कर फूला (Sabh par kripa dristi kar phoola)', 'He looks upon everyone with a merciful eye and is pleased with His creation.', 'The Lord looks on all creation with mercy, grace, and delight.', 'You are seen by a Creator who delights in showing mercy and kindness.', 0, NULL, '["mercy","grace","kindness"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-046', 'chaupai_sahib', 'Sant Paye Dukh Paye', 52, NULL, 'संत पाए दुख पाए दुखी (Sant paye dukh paye)', 'The Lord feels pained when His saintly devotees are in pain.', 'The Divine is deeply connected to faithful seekers and feels their sorrow as His own.', 'There is a profound empathetic bond between the seeker and the Divine.', 0, NULL, '["devotees","empathy","bond"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-047', 'chaupai_sahib', 'Sukh Paye Sadhun Ke Sukhi', 53, NULL, 'सुख पाए साधुन के सुखी (Sukh paye sadhun ke sukhi)', 'He feels happy when holy and virtuous people are happy.', 'The Lord experiences joy when the virtuous and saintly live in happiness.', 'Your spiritual growth and joy are precious to the Divine.', 0, NULL, '["virtue","joy","growth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-048', 'chaupai_sahib', 'Ek Ek Ki Peer Pachhanai', 54, NULL, 'एक एक की पीर पछानै (Ek ek ki peer pachhanai)', 'He understands the suffering and pain of every single living being.', 'Each individual''s unique struggle is personally known and understood by the Almighty.', 'Your specific pain is seen by a Power with capacity to heal it.', 0, NULL, '["healing","pain","compassion"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-049', 'chaupai_sahib', 'Ghat Ghat Ke Pat Pat Ki Janai', 55, NULL, 'घट घट के पट पट की जानै (Ghat ghat ke pat pat ki janai)', 'He knows every secret and every layer within every heart.', 'God knows every hidden secret and subtle layer of human consciousness.', 'True spiritual work happens in the hidden layers of the heart.', 0, NULL, '["inner-life","secrets","awareness"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-050', 'chaupai_sahib', 'Jab Udkarakh Kara Kartara', 56, NULL, 'जब उदकरख करा करतारा (Jab udkarakh kara kartara)', 'When the Creator expands His creation.', 'This line describes the moment the Creator chooses to manifest and expand the universe.', 'The physical world is a deliberate act of Divine expansion and Will.', 0, NULL, '["creation","expansion","divine-will"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-051', 'chaupai_sahib', 'Praja Dharat Tab Deha Apara', 57, NULL, 'प्रजा धरत तब देह अपारा (Praja dharat tab deha apara)', 'Then the creation takes on countless and uncounted physical forms.', 'When the Creator expands creation, beings manifest in an infinite variety of physical bodies.', 'Every living form is a deliberate expression of the Divine''s expansive creative power.', 0, NULL, '["creation","forms","divine-expression"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-052', 'chaupai_sahib', 'Jab Akarkh Karat Ho Kabhoo', 58, NULL, 'जब आकर्ख करत हो कबहूं (Jab akarkh karat ho kabhoo)', 'And whenever You withdraw Your creation into Yourself.', 'This refers to the moment when the Almighty chooses to dissolve manifest creation.', 'As the universe expands, it also returns to its Source; only the Creator is permanent.', 0, NULL, '["dissolution","source","impermanence"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-053', 'chaupai_sahib', 'Tum Mai Milat Deha Dhar Sabhhoo', 59, NULL, 'तुम में मिलत देह धर सबहूं (Tum mai milat deha dhar sabhhoo)', 'All physical beings merge back into Your Divine Light.', 'Every creature eventually returns and merges into the Divine Light.', 'Our final destination is return to the same Divine Light from which we came.', 0, NULL, '["divine-light","return","unity"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-054', 'chaupai_sahib', 'Jete Badan Srisht Sabh Dharai', 60, NULL, 'जेते बदन सृष्टि सभ धारै (Jete badan srisht sabh dharai)', 'All the physical bodies that exist in this world.', 'This includes every manifested shape and form in the universe.', 'No physical existence is separate from the Creator''s grand design.', 0, NULL, '["bodies","manifestation","design"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-055', 'chaupai_sahib', 'Aap Aapni Boojh Ucharai', 61, NULL, 'आप आपनी बूझ उचारै (Aap aapni bujh ucharai)', 'Praise You according to their own capacity and understanding.', 'Every being praises the Lord according to their own limited wisdom and approach.', 'Your relationship with God is unique and can grow from your present level of understanding.', 0, NULL, '["understanding","praise","individual-path"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-056', 'chaupai_sahib', 'Tum Sabh Hi Te Rehat Niralamb', 62, NULL, 'तुम सभ ही ते रहत निरालम (Tum sabh hi te rehat niralamb)', 'O Lord, You remain detached and unaffected by all these things.', 'The Almighty remains detached and unaffected by praise or criticism.', 'Spiritual steadiness grows when you remain centered beyond external opinions.', 0, NULL, '["detachment","equanimity","stability"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-057', 'chaupai_sahib', 'Janat Ved Bhed Ar Aalam', 63, NULL, 'जानत वेद भेद अर आलम (Janat Ved bhed ar aalam)', 'Only the Vedas and the truly learned scholars know this secret.', 'This subtle mystery is understood through deep spiritual study and realized wisdom.', 'To understand the Divine more deeply, seek wisdom beyond surface-level appearances.', 0, NULL, '["wisdom","study","mystery"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-058', 'chaupai_sahib', 'Nirankar Nirvikar Niralambh', 64, NULL, 'निरंकार निर्विकार निरलम (Nirankar nirvikar niralambh)', 'The Lord is Formless, free from all vices, and completely detached.', 'God has no shape, is free of all defects, and remains independent of worldly limitations.', 'Spiritual growth means moving toward purity and freedom from destructive tendencies.', 0, NULL, '["formless","purity","detachment"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-059', 'chaupai_sahib', 'Aadi Aneel Anaadi Asambh', 65, NULL, 'आदि अनील अनादि असंभव (Aadi aneel anaadi asambh)', 'He is the Primal Being, stainless, without beginning, and self-existent.', 'The Lord is the original root of all, without stain, beginning, or dependence.', 'You can find deep security in a Power that has always existed and never ends.', 0, NULL, '["primal","eternal","security"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-060', 'chaupai_sahib', 'Ta Ko Moorh Ucharat Bheda', 66, NULL, 'ता को मूढ़ उचारत भेदा (Ta ko moorh ucharat bheda)', 'Fools claim to know His secrets and mysteries.', 'Only those lacking wisdom claim to have fully decoded the Almighty.', 'Humility is the beginning of wisdom before the Infinite.', 0, NULL, '["humility","mystery","wisdom"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-061', 'chaupai_sahib', 'Ja Ko Bhev Na Pavat Veda', 67, NULL, 'जा को भेव न पावत वेदा (Ja ko bhev na pavat veda)', 'While even the Vedas cannot find His ultimate limit or secret.', 'Even ancient scriptures cannot reach the complete end of the Creator''s mystery.', 'The more you learn of God, the more you discover endless depth.', 0, NULL, '["vedas","infinite","depth"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-062', 'chaupai_sahib', 'Ta Ko Kar Pahan Anumanat', 68, NULL, 'ता को करि पाहन अनुमानत (Ta ko kar pahan anumanat)', 'Some fools mistakenly imagine and worship Him as a stone idol.', 'Ignorance tries to limit the vast, formless Lord to a physical object.', 'Do not confine the Infinite to a single symbol or form.', 0, NULL, '["formless","idolatry","infinite"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-063', 'chaupai_sahib', 'Maha Moorh Kachhu Bhed Na Janat', 69, NULL, 'महा मूढ़ कछु भेद न जानत (Maha moorh kachhu bhed na janat)', 'These great fools do not know any of the Lord''s true secrets.', 'Those who confine God to form remain unaware of His deeper spiritual essence.', 'Outer forms are empty if they block the search for inner Reality.', 0, NULL, '["essence","inner-reality","discernment"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-064', 'chaupai_sahib', 'Mahadev Ko Kehat Sada Shiv', 70, NULL, 'महादेव को कहत सदा शिव (Mahadev ko kehat sada Shiv)', 'Many call Mahadev (Shiva) the eternal and welfare-giving God.', 'Some people regard Shiva as the ultimate eternal Creator.', 'Distinguish manifest spiritual forms from the Formless Source behind all.', 0, NULL, '["discernment","source","formless"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-065', 'chaupai_sahib', 'Nirankar Ka Cheenat Nahi Bhiv', 71, NULL, 'निरंकार का चीनत नहिं भिव (Nirankar ka cheenat nahi bhiv)', 'But they do not recognize the true secret of the Formless Lord.', 'The secret of Nirankar, without shape or boundary, remains unrecognized.', 'Seeing God''s formless nature helps you sense His presence everywhere.', 0, NULL, '["nirankar","formless","awareness"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-066', 'chaupai_sahib', 'Aap Aapni Budh Hai Jeti', 72, NULL, 'आप आपनी बुध है जेती (Aap aapni budh hai jeti)', 'According to whatever wisdom or intelligence a person possesses.', 'Each person interprets the Divine according to their own level of understanding.', 'Your vision of God is shaped by your mind, so keep refining it with humility.', 0, NULL, '["understanding","mind","humility"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-067', 'chaupai_sahib', 'Barnat Bhinn Bhinn Tuhe Teti', 73, NULL, 'बरनत भिन्न भिन्न तुहे तेती (Barnat bhinn bhinn tuhe teti)', 'They describe You in many different and varied ways.', 'Different minds produce different descriptions of the same one God.', 'Hold respectful openness toward varied attempts to describe the Infinite.', 0, NULL, '["diversity","tolerance","one-god"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-068', 'chaupai_sahib', 'Tumra Lakha Na Jaye Pasara', 74, NULL, 'तुमरा लखा न जाए पसारा (Tumra lakha n jaye pasara)', 'Your vast expansion and creation cannot be fully understood or seen.', 'No human has capacity to fully grasp the entire extent of God''s creation.', 'Peace comes from accepting we are small parts of a vast Divine whole.', 0, NULL, '["vastness","acceptance","peace"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-069', 'chaupai_sahib', 'Keh Bidh Saja Pratham Sansara', 75, NULL, 'केहि बिधि सजा प्रथम संसारा (Keh bidh saja pratham sansara)', 'How the world was first created remains a mystery beyond human knowledge.', 'The exact way the universe first came into being is known only to the Creator.', 'Some mysteries are invitations to live with wonder and faith.', 0, NULL, '["mystery","wonder","faith"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-070', 'chaupai_sahib', 'Ekae Roop Anoop Saroopa', 76, NULL, 'एकै रूप अनूप सरूपा (Ekae roop anoop saroopa)', 'You have one matchless and beautiful form.', 'Though appearing in countless ways, the Divine remains uniquely incomparable.', 'Behind all diversity is one beautiful Divine Source.', 0, NULL, '["unity","beauty","source"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-091', 'chaupai_sahib', 'Riddhi Siddhi Ghar Mo Sabh Hoye', 91, NULL, 'रिद्धि सिद्धि घर मों सभ होई (Riddhi siddhi ghar mo sabh hoye)', 'All spiritual and worldly powers (Riddhi-Siddhi) reside in their homes.', 'For those who receive God''s grace, success and spiritual powers follow naturally like servants in their home.', 'When you prioritize connection with the Divine, abundance follows as a byproduct.', 0, NULL, '["grace","abundance","riddhi-siddhi"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-092', 'chaupai_sahib', 'Dust Chhah Chhui Sakai Na Koi', 92, NULL, 'दुष्ट छांह छुइ सकै न कोई (Dust chhah chhui sakai na koi)', 'No wicked person or vice can even touch their shadow.', 'Divine protection becomes so complete that external negativity and internal vices cannot come near.', 'A faith-anchored life creates a field of peace that negativity cannot penetrate.', 0, NULL, '["protection","peace","faith"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-093', 'chaupai_sahib', 'Ek Baar Jin Tumae Sambhara', 93, NULL, 'एक बार जिन तुमै संभारा (Ek baar jin tumae sambhara)', 'Whoever remembers You even once and takes Your support.', 'The Lord values even one sincere, heart-centered moment of remembrance and surrender.', 'Sincerity in prayer matters more than repetition without presence.', 0, NULL, '["remembrance","sincerity","surrender"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-094', 'chaupai_sahib', 'Kaal Paas Te Tahi Ubara', 94, NULL, 'काल फास ते ताहि उबारा (Kaal paas te tahi ubara)', 'You liberate them from the noose of death and the cycle of rebirth.', 'The Lord rescues sincere seekers from fear of mortality and repetitive cycles of existence.', 'Spiritual freedom begins when fear of time and death loosens its grip.', 0, NULL, '["liberation","mortality","freedom"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-095', 'chaupai_sahib', 'Jin Nar Naam Tiharo Kaha', 95, NULL, 'जिन नर नाम तिहारो कहा (Jin nar naam tiharo kaha)', 'People who utter Your Name and take Your support.', 'These are people who rely on the Divine Name as their steady source of strength and direction.', 'Let the Divine Name become your daily anchor in a changing world.', 0, NULL, '["naam","anchor","guidance"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-096', 'chaupai_sahib', 'Darid Dust Dokh Te Raha', 96, NULL, 'दारिद दुष्ट दोख ते रहा (Darid dust dokh te raha)', 'Remain safe from poverty, wicked people, and all vices.', 'Those who take support of the Name are protected from material lack, social harm, and spiritual decay.', 'Faith can become a holistic shield for physical, social, and spiritual well-being.', 0, NULL, '["protection","wellbeing","naam"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-097', 'chaupai_sahib', 'Khadagket Mai Sharan Tihari', 97, NULL, 'खड़ग केत मैं शरण तिहारी (Khadagket mai sharan tihari)', 'O Bearer of the Sword of Justice, I have come to Your shelter.', 'The devotee enters refuge in the One who protects righteousness with justice and mercy.', 'Surrender means trusting your life to a Power that is compassionate and just.', 0, NULL, '["justice","shelter","surrender"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-098', 'chaupai_sahib', 'Aap Hath Dai Lehu Ubari', 98, NULL, 'आप हाथ दै लेहु उबारी (Aap hath dai lehu ubari)', 'Please give me Your hand and save me from my negative impulses.', 'A direct plea for personal rescue from the five inner vices that disturb the mind.', 'Admitting you cannot overcome deep habits alone opens the door to Divine help.', 0, NULL, '["vices","help","rescue"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-099', 'chaupai_sahib', 'Sakal Thaur Mo Hohu Sahai', 99, NULL, 'सकल ठौर मो होहु सहाई (Sakal thaur mo hohu sahai)', 'Be my helper and support in every place.', 'The devotee asks for Divine companionship and help in every place and situation.', 'Divine support is available everywhere, not only in sacred spaces.', 0, NULL, '["support","companionship","everywhere"]');
INSERT INTO chaupai_verses (id, source_type, title, day_index, date, gurmukhi_text, english_meaning, simple_explanation, life_reflection, is_featured, audio_file_name, tags_json) VALUES ('chaupai-100', 'chaupai_sahib', 'Dust Dokh Te Lehu Bachai', 100, NULL, 'दुष्ट दोख ते लेहु बचाई (Dust dokh te lehu bachai)', 'Save me from the suffering caused by wicked people and internal vices.', 'A concluding plea for complete protection from both outer negativity and inner shortcomings.', 'Lasting peace comes from being guarded against both external troubles and inner restlessness.', 0, NULL, '["protection","inner-peace","vices"]');
